export const mockData = [
  {
    id: 1,
    firstName: "John",
    lastName: "Doe",
    yearOfBirth: 1990,
  },
  {
    id: 2,
    firstName: "Sarah",
    lastName: "Smith",
    yearOfBirth: 1985,
  },
  {
    id: 3,
    firstName: "Michael",
    lastName: "Johnson",
    yearOfBirth: 1978,
  },
  {
    id: 4,
    firstName: "Emily",
    lastName: "Davis",
    yearOfBirth: 1992,
  },
  {
    id: 5,
    firstName: "David",
    lastName: "Brown",
    yearOfBirth: 1982,
  },
  {
    id: 6,
    firstName: "Jessica",
    lastName: "Wilson",
    yearOfBirth: 1995,
  },
  {
    id: 7,
    firstName: "Robert",
    lastName: "Anderson",
    yearOfBirth: 1973,
  },
  {
    id: 8,
    firstName: "Olivia",
    lastName: "Thomas",
    yearOfBirth: 1988,
  },
  {
    id: 9,
    firstName: "William",
    lastName: "Lee",
    yearOfBirth: 1998,
  },
  {
    id: 10,
    firstName: "Sophia",
    lastName: "Clark",
    yearOfBirth: 1991,
  },
  {
    id: 11,
    firstName: "James",
    lastName: "Lewis",
    yearOfBirth: 1980,
  },
  {
    id: 12,
    firstName: "Ava",
    lastName: "Walker",
    yearOfBirth: 1993,
  },
  {
    id: 13,
    firstName: "Benjamin",
    lastName: "Green",
    yearOfBirth: 1975,
  },
  {
    id: 14,
    firstName: "Mia",
    lastName: "Hall",
    yearOfBirth: 1987,
  },
  {
    id: 15,
    firstName: "Ethan",
    lastName: "Young",
    yearOfBirth: 1984,
  },
  {
    id: 16,
    firstName: "Charlotte",
    lastName: "Baker",
    yearOfBirth: 1996,
  },
  {
    id: 17,
    firstName: "Alexander",
    lastName: "Harris",
    yearOfBirth: 1979,
  },
  {
    id: 18,
    firstName: "Amelia",
    lastName: "Nelson",
    yearOfBirth: 1994,
  },
  {
    id: 19,
    firstName: "Daniel",
    lastName: "Wright",
    yearOfBirth: 1983,
  },
  {
    id: 20,
    firstName: "Harper",
    lastName: "Martin",
    yearOfBirth: 1997,
  },
];
